project:
  type: website
  output-dir: docs

website:
  title: "WhaleWatch"
  navbar:
    right:
      - href: index.qmd
        text: " "
      - href: about.qmd
        text: About WhaleWatch 2.0
      - href: products.qmd
        text: WhaleWatch 2.0 Products
      - href: explorer.qmd
        text: WhaleWatch 2.0 Explorer

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    include-after-body: footer.html



