---
title: "WhaleWatch 2.0 Explorer"
anchor-sections: false
format:
  html:
    theme: lux
    toc: false
    page-layout: full
---

::: {.whale-card}

<details class="whale-buttons">
<summary><strong>Information & Instructions</strong></summary>
<p></p>
WhaleWatch 2.0 Explorer gives users an opportunity to explore historical trends in the WhaleWatch 2.0 Map product.

- Select historical date of interest.
- Download georeferenced data (raster GRID).
- Customize the display: use dropdowns to change map extent, or to visualize the shipping lanes used to calculate the WhaleWatch Shipping Lanes Indicator.

</details>

---

<iframe 
  src="https://heatherwelch.shinyapps.io/benioff_app/" 
  width="100%" 
  height="800" 
  style="border:none; border-radius:6px;">
</iframe>

If the embedded app does not load,  [open WhaleWatch 2.0 Explorer](https://heatherwelch.shinyapps.io/benioff_app/).

:::


::: {.whale-disclaimer}
The information on this page may be used and redistributed freely, but is not intended for legal use. Neither the data contributors, WhaleWatch 2.0 partner organizations, CoastWatch, NOAA SWFSC, nor any of their employees or contractors, makes any warranty, express or implied, including warranties of merchantability and fitness for a particular purpose, or assumes any legal liability for the accuracy, completeness, or usefulness of this information. Although it is distributed by the NOAA CoastWatch West Coast Regional Node, this product is solely the responsibility of the WhaleWatch 2.0 project and is not associated with NOAA CoastWatch. For official information about WhaleWatch 2.0 contact [Briana Abrahms](https://coastwatch.pfeg.noaa.gov/whalewatch2/mailto@briana.abrahms@noaa.gov?Subject=EcoCast), [Elliott Hazen](https://coastwatch.pfeg.noaa.gov/whalewatch2/mailto@elliott.hazen@noaa.gov?Subject=EcoCast), or [Heather Welch](https://coastwatch.pfeg.noaa.gov/whalewatch2/mailto@heather.welch@noaa.gov?Subject=EcoCast).
:::
